### shiny test
app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(intro = "click")
app$setInputs(`btn-117825024` = "click")
app$setInputs(side = "Tail")
app$setInputs(side = "Head")
app$setInputs(prob = 0.52)
app$setInputs(prob = 0.63)
app$setInputs(prob = 0.62)
app$setInputs(prob = 0.44)
app$setInputs(prob = 0.46)
app$setInputs(prob = 0.5)
app$setInputs(prob = 0.51)
app$setInputs(prob = 0.5)
app$setInputs(init_stake = 50)
app$setInputs(init_stake = 30)
app$setInputs(win_target = 60)
app$setInputs(win_target = 100)
app$setInputs(win_target = 60)
app$setInputs(simul = 7680)
app$setInputs(simul = 911)
app$setInputs(rep_sim = "click")
app$setInputs(rep_sim = "click")
app$setInputs(rep_sim = "click")
app$setInputs(rep_sim = "click")
app$setInputs(rep_sim = "click")
app$setInputs(dist = "click")
app$setInputs(chance = "click")
app$snapshot()
app$snapshot()
app$setInputs(`btn-117825024` = "click")
